# Change these first
owner: jessica-habaneros # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Habaneros
    url: https://habaneros.ch
  - name: Garage Union
    url: https://garageunion.ch
  - name: Boucherie La Lienne
    url: https://boucherielalienne.ch
  - name: Pascal Héritier
    url: https://pascal-heritier.ch
  - name: RR Jantes
    url: https://rrjantes.ch
  - name: Serveur S1
    url: https://s1.stevenroh.ch
    expectedStatusCodes:
      - 404
  - name: Serveur S2
    url: https://s2.stevenroh.ch
    expectedStatusCodes:
      - 404
    

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  logoUrl: https://habaneros.ch/wp-content/uploads/2023/03/logo_habaneros.svg
  baseUrl: /uptime # where "repo" is your repository name
  name: uptime
  introTitle: ""
  introMessage: ""
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
